### ISSUE TITLE
Debug IT failure on Travis

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/deposit-services#168]
Uncovered by this PR https://github.com/OA-PASS/deposit-services/pull/167, but is seemingly unrelated

**Comment by Trumbore** [comment]
It was confirmed on three systems (Ben's Windows, Ben's CentOS and Jim's system) that the deposit service ITs failed when run as a suite.  Specifically, tests SubmissionProcessorIT and DepositProcessorIT reported that the expected number of submissions weren't created.

If these test are run stand-alone, they pass on user systems, with the implication being that some previous test has polluted the environment for these tests.  Travis also fails on DepositProcessorIT in a slightly different way, presumable from the same cause.

The root cause of the failure was not identified, and pursuit of that cause (and a solution for it) are tabled for now.
