### ISSUE TITLE
Cut new release after adding support for new metadata schema and enable PackageProvider

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/deposit-services#221]
0.5d LE

**Comment by emetsger** [comment]
The Docker image used in testing is `oapass/deposit-pass-docker:1.0.0-3.4-SNAPSHOT@sha256:299e8c6bb8a861e2147f13d728fee898e61d2be5554ae405d8ddb29b50419fe8
` according to the [CMF rollout doc](https://docs.google.com/document/d/1jWRk6_k6BvxDHkNDG-q25vieu-6i8AEF4U-NlcVFaLU/edit#).

The code used in that Docker image is no longer the tip of `master`, so a `1.0.0-3.4-maint` branch has been [prepared](https://github.com/OA-PASS/deposit-services/tree/1.0.0-3.4-maint), which branches from `master` at `a9df23` (`a9df23` is the commit in that image).  The `1.0.0-3.4-maint` branch will be used to cut the release.

There have been some bugs fixed since that image was used for testing, so those commits ought to be included in the release.

**Comment by emetsger** [comment]
Release of core deposit services is complete from the `1.0.0-3.4-maint` branch:
- https://github.com/OA-PASS/deposit-services/releases/tag/1.0.0-3.4

Package providers needs to be released next, followed by a PR to `pass-docker`
